import { config } from '../config.js';
import type { ChartSpec } from '@vd/shared';
import { loadSemanticLayer } from '../semantic/load.js';
import { resolveFilters } from '../semantic/resolve.js';
import { resolveTimeRange } from '../semantic/time.js';
import { compileSql } from '../semantic/compile.js';

let sessionToken: string | null = null;

async function getMetabaseSession(): Promise<string> {
  if (sessionToken) return sessionToken;

  const url = `${config.METABASE_URL?.replace(/\/$/, '')}/api/session`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      username: config.METABASE_USER,
      password: config.METABASE_PASSWORD,
    }),
  });

  if (!res.ok) {
    throw new Error(`Metabase auth failed: ${res.statusText}`);
  }

  const data = (await res.json()) as { id: string };
  sessionToken = data.id;
  return sessionToken;
}

function mapDisplayType(chartType: string): string {
  switch (chartType) {
    case 'line':
      return 'line';
    case 'area':
      return 'area';
    case 'donut':
      return 'pie';
    case 'bar':
    case 'stacked_bar':
    default:
      return 'bar';
  }
}

export async function exportDashboardToMetabase(
  title: string,
  charts: ChartSpec[]
): Promise<{ url: string }> {
  if (!config.METABASE_URL) {
    throw new Error('METABASE_URL is not configured');
  }

  const token = await getMetabaseSession();
  const baseUrl = config.METABASE_URL.replace(/\/$/, '');
  const dbId = config.METABASE_DB_ID ? parseInt(config.METABASE_DB_ID, 10) : 1;
  const semantic = loadSemanticLayer();

  // 1. Create Dashboard
  const dashRes = await fetch(`${baseUrl}/api/dashboard`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Metabase-Session': token,
    },
    body: JSON.stringify({
      name: title || `Voice Dashboard ${new Date().toISOString().slice(0, 10)}`,
      description: 'Auto-generated by Voice Analytics Assistant',
    }),
  });

  if (!dashRes.ok) {
    throw new Error(`Failed to create Metabase dashboard: ${dashRes.statusText}`);
  }

  const dashboard = (await dashRes.json()) as { id: number };

  const dimMap: Record<string, string> = {};
  for (const [k, d] of Object.entries(semantic.dimensions)) {
    dimMap[k.toLowerCase()] = d.column;
  }

  // 2. Create cards and attach
  let cardIdx = 0;
  for (const chart of charts) {
    const metricDef = semantic.metrics[chart.metric];
    if (!metricDef) continue;

    const timeRange = resolveTimeRange(chart.time_range, config.AS_OF_DATE);
    const filterRes = resolveFilters(chart.filters, semantic);
    const resolvedFilters = filterRes.ok ? filterRes.filters : [];

    const compiled = compileSql({
      metricId: chart.metric,
      metricDef,
      timeColumn: semantic.time_column,
      sourceTable: semantic.source,
      timeRange,
      groupBy: chart.group_by,
      dimensionColumn: chart.group_by ? semantic.dimensions[chart.group_by]?.column : undefined,
      timeGranularity: chart.time_granularity,
      resolvedFilters,
      dimensionColumnMap: dimMap,
    });

    const cardRes = await fetch(`${baseUrl}/api/card`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Metabase-Session': token,
      },
      body: JSON.stringify({
        name: chart.title || `${metricDef.label}`,
        dataset_query: {
          database: dbId,
          type: 'native',
          native: {
            query: compiled.displaySql,
          },
        },
        display: mapDisplayType(chart.chart_type),
        visualization_settings: {},
      }),
    });

    if (cardRes.ok) {
      const card = (await cardRes.json()) as { id: number };
      const col = (cardIdx % 2) * 9;
      const row = Math.floor(cardIdx / 2) * 6;

      await fetch(`${baseUrl}/api/dashboard/${dashboard.id}/cards`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Metabase-Session': token,
        },
        body: JSON.stringify({
          cardId: card.id,
          row,
          col,
          size_x: 9,
          size_y: 6,
        }),
      });
      cardIdx++;
    }
  }

  return { url: `${baseUrl}/dashboard/${dashboard.id}` };
}
